# Generated by Django 6.0.3 on 2026-03-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_review_time',
            field=models.TimeField(blank=True, help_text='Preferred time to be reminded for daily review', null=True),
        ),
    ]
