# Generated by Django 6.0.2 on 2026-02-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=63)),
                ('pronunciation', models.CharField(max_length=63)),
                ('definition', models.TextField()),
                ('purpose', models.CharField(choices=[('noun', 'Noun'), ('pronoun', 'Pronoun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb')], default='noun', max_length=20)),
            ],
        ),
    ]
