# Generated by Django 6.0.2 on 2026-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakNoy', '0002_alter_flashcard_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='purpose',
            field=models.CharField(choices=[('Noun', 'Noun'), ('Pronoun', 'Pronoun'), ('Verb', 'Verb'), ('Adjective', 'Adjective'), ('Adverb', 'Adverb')], default='Noun', max_length=20),
        ),
    ]
