# Generated by Django 6.0.2 on 2026-02-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakNoy', '0003_alter_flashcard_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='cardtype',
            field=models.CharField(choices=[('Universal', 'Universal'), ('Custom', 'Custom')], default='Custom', max_length=9),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='dialect',
            field=models.CharField(choices=[('Cebuano', 'Cebuano'), ('Ilocano', 'Ilocano')], default=None, max_length=20),
        ),
    ]
