# Generated by Django 6.0.2 on 2026-02-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakNoy', '0004_flashcard_cardtype_flashcard_dialect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='purpose',
            field=models.CharField(choices=[('Noun', 'Noun'), ('Pronoun', 'Pronoun'), ('Verb', 'Verb'), ('Adjective', 'Adjective'), ('Adverb', 'Adverb'), ('Expression', 'Expression')], default='Noun', max_length=20),
        ),
    ]
