# Generated by Django 6.0.2 on 2026-03-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakNoy', '0005_alter_flashcard_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='dialect',
            field=models.CharField(choices=[('Cebuano', 'Cebuano'), ('Ilocano', 'Ilocano')], default='Cebuano', max_length=20),
        ),
    ]
