# Generated by Django 6.0.2 on 2026-04-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakNoy', '0006_alter_flashcard_dialect'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('flashcards', models.ManyToManyField(blank=True, related_name='collections', to='SpeakNoy.flashcard')),
            ],
        ),
    ]
