# Generated by Django 5.1.6 on 2026-04-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakNoy', '0007_flashcardcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flashcardcollection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PublicSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('collections', models.ManyToManyField(blank=True, related_name='publicspace_collections', to='SpeakNoy.flashcardcollection')),
                ('flashcards', models.ManyToManyField(blank=True, related_name='publicspace_flashcards', to='SpeakNoy.flashcard')),
            ],
        ),
    ]
