# Generated by Django 5.1.6 on 2026-04-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeakNoy', '0009_flashcard_creator_flashcardcollection_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
